/************************************************************\
 **     Copyright (c) 2012-2023 Anlogic Inc.
 **  All Right Reserved.\
\************************************************************/
/************************************************************\
 ** Log	:	This file is generated by Anlogic IP Generator.
 ** File	:	/data/Tasks/FrequencyResponseDetector/td/al_ip/sys_pll.v
 ** Date	:	2023 07 06
 ** TD version	:	5.6.71036
\************************************************************/

///////////////////////////////////////////////////////////////////////////////
//	Input frequency:             100.000MHz
//	Clock multiplication factor: 18
//	Clock division factor:       1
//	Clock information:
//		Clock name	| Frequency 	| Phase shift
//		C0        	| 200.000000MHZ	| 0  DEG     
//		C1        	| 64.285714 MHZ	| 0  DEG     
//		C2        	| 120.000000MHZ	| 0  DEG     
///////////////////////////////////////////////////////////////////////////////
`timescale 1 ns / 100 fs

module sys_pll (
  refclk,
  reset,
  lock,
  clk0_out,
  clk1_out,
  clk2_out 
);

  input refclk;
  input reset;
  output lock;
  output clk0_out;
  output clk1_out;
  output clk2_out;

  wire clk0_buf;
  wire clk1_buf;
  wire clk2_buf;

  PH1_LOGIC_BUFG bufg_c0 (
    .i(clk0_buf),
    .o(clk0_out) 
  );

  PH1_LOGIC_BUFG bufg_c1 (
    .i(clk1_buf),
    .o(clk1_out) 
  );

  PH1_LOGIC_BUFG bufg_c2 (
    .i(clk2_buf),
    .o(clk2_out) 
  );

  PH1_PHY_PLL #(
    .DYN_PHASE_PATH_SEL("DISABLE"),
    .DYN_FPHASE_EN("DISABLE"),
    .MPHASE_ENABLE("DISABLE"),
    .FIN("100.000"),
    .FEEDBK_MODE("NOCOMP"),
    .FBKCLK("VCO_PHASE0"),
    .FBKCLK_INT("VCO_PHASE0"),
    .PLL_FEED_TYPE("INTERNAL"),
    .PLL_USR_RST("ENABLE"),
    .GMC_GAIN(3),
    .ICP_CUR(13),
    .LPF_CAP(2),
    .LPF_RES(1),
    .REFCLK_DIV(1),
    .FBCLK_DIV(18),
    .CLKC0_ENABLE("ENABLE"),
    .CLKC0_DIV(9),
    .CLKC0_CPHASE(8),
    .CLKC0_FPHASE(0),
    .CLKC0_FPHASE_RSTSEL(0),
    .CLKC0_DUTY_INT(5),
    .CLKC0_DUTY50("ENABLE"),
    .CLKC1_ENABLE("ENABLE"),
    .CLKC1_DIV(28),
    .CLKC1_CPHASE(27),
    .CLKC1_FPHASE(0),
    .CLKC1_FPHASE_RSTSEL(0),
    .CLKC1_DUTY_INT(14),
    .CLKC1_DUTY50("ENABLE"),
    .CLKC2_ENABLE("ENABLE"),
    .CLKC2_DIV(15),
    .CLKC2_CPHASE(14),
    .CLKC2_FPHASE(0),
    .CLKC2_FPHASE_RSTSEL(0),
    .CLKC2_DUTY_INT(8),
    .CLKC2_DUTY50("ENABLE"),
    .INTPI(2),
    .HIGH_SPEED_EN("DISABLE"),
    .SSC_ENABLE("DISABLE"),
    .SSC_MODE("CENTER"),
    .SSC_AMP(0.0000),
    .SSC_FREQ_DIV(0),
    .SSC_RNGE(0),
    .FRAC_ENABLE("DISABLE"),
    .DITHER_ENABLE("DISABLE"),
    .SDM_FRAC(0) 
  ) pll_inst (
    .refclk(refclk),
    .pllreset(reset),
    .lock(lock),
    .pllpd(1'b0),
    .refclk_rst(1'b0),
    .wakeup(1'b0),
    .psclk(1'b0),
    .psdown(1'b0),
    .psstep(1'b0),
    .psclksel(3'b000),
    .psdone(open),
    .cps_step(2'b00),
    .drp_clk(1'b0),
    .drp_rstn(1'b1),
    .drp_sel(1'b0),
    .drp_rd(1'b0),
    .drp_wr(1'b0),
    .drp_addr(8'b00000000),
    .drp_wdata(8'b00000000),
    .drp_err(open),
    .drp_rdy(open),
    .drp_rdata({open, open, open, open, open, open, open, open}),
    .fbclk(1'b0),
    .clkc({open, open, open, open, open, clk2_buf, clk1_buf, clk0_buf}),
    .clkcb({open, open, open, open, open, open, open, open}),
    .clkc_en({8'b00000111}),
    .clkc_rst(2'b00),
    .ext_freq_mod_clk(1'b0),
    .ext_freq_mod_en(1'b0),
    .ext_freq_mod_val(17'b00000000000000000),
    .ssc_en(1'b0) 
  );

endmodule

